base:
  build: .
  volumes:
    - ./etc/kafka:/etc/kafka:ro

zookeeper-data:
  extends: busybox
  volumes:
    - /zk-data
  labels:
    io.rancher.container.start_once: 'true'

kafka-data:
  extends: busybox
  volumes:
    - /kafka-data
  labels:
    io.rancher.container.start_once: 'true'

zookeeper:
  extends: base
  hostname: confluent-zookeeper
  command: zookeeper-server-start /etc/kafka/zookeeper.properties
  ports:
    - "2181:2181"
  volumes_from:
    - "zookeeper-data"
  labels:
    io.rancher.sidekicks: zookeeper-data


kafka:
  extends: base
  hostname: confluent-kafka
  command: kafka-server-start /etc/kafka/server.properties
  links:
    - "zookeeper"
  volumes_from:
    - "kafka-data"
  labels:
    io.rancher.sidekicks: kafka-data
    io.rancher.container.dns: 'true'
  net: host

kafka-manager:
  image: sheepkiller/kafka-manager
  ports:
    - 9000:9000/tcp
  environment:
    APPLICATION_SECRET: letmein
    ZK_HOSTS: confluent-zookeeper:2181
  labels:
    io.rancher.container.pull_image: always
  command:
  - -Djava.net.preferIPv4Stack=true
