
zookeeper-data:
  image: busybox
  volumes:
    - /zk-data
  labels:
    io.rancher.container.start_once: 'true'

kafka-data:
  image: busybox
  volumes:
    - /kafka-data
  labels:
    io.rancher.container.start_once: 'true'

zookeeper:
  build: https://github.com/ceason/rancher-kafka.git
  command: zookeeper-server-start /etc/kafka/zookeeper.properties
  ports:
    - "2181:2181"
  volumes_from:
    - "zookeeper-data"
  labels:
    io.rancher.sidekicks: zookeeper-data
    io.rancher.container.pull_image: always


kafka:
  build: https://github.com/ceason/rancher-kafka.git
  command: kafka-server-start /etc/kafka/server.properties
  links:
    - "zookeeper"
  volumes_from:
    - "kafka-data"
  labels:
    io.rancher.sidekicks: kafka-data
    io.rancher.container.dns: 'true'
    io.rancher.container.pull_image: always
  net: host

kafka-manager:
  image: sheepkiller/kafka-manager
  command:
  - -Djava.net.preferIPv4Stack=true
  ports:
    - 9000:9000/tcp
  links:
    - "zookeeper"
  environment:
    APPLICATION_SECRET: letmein
    ZK_HOSTS: zookeeper:2181
  labels:
    io.rancher.container.pull_image: always
